### PR TITLE
feat/adding comments

### LINKED ISSUE #71: Event Rating and Comments - For Previous and Current events
**Describe the feature**
A user should be able to comment on and view comments on upcoming events. A user should also be able to comment on and rate events that have already happened for a period of time.

**Possible implementation(s)**
Possibly in the detailed view of an event, a user should be able to input a comment to the event and view other users comments. They may also be able to view events that they were interested in and happened within an amount of time ago (e.g. 48 hours ago) and still comment and rate them. Possibly a rating out of 5, similar to movies. The event should also have an average rating from users rating of it that will be displayed on the details view (of course, this can only be visible after the event has happened, as you cannot rate an event that has not yet happened.

**Additional context**
Many social media apps allow users to comment on other users media, such as Instagram or Facebook. Check them out for inspiration on the commenting feature! For the rating feature, we were imagining something similar to a movie rating. Check out apps like LetterBoxd for similar rating features!

### PR DESCRIPTION
**Pull request by tmur647**
add functionality for creating and deleting comments from the detailed page of an event to work towards #71

### CODE REVIEW

**Review by deir905 — CHANGES_REQUESTED** [review]
I gave it a run on my machine and it appears to working. Awesome work.

Some SonarCloud code smells which are easy to fix.

**EDIT:**
There is a bug where navigating to the detail event fragment from the interested events fragment or friend's events page wont show the comments.

**Comment by tmur647** [comment]
sweet think I fixed bug, for some reason interested events has a stored events list that doesnt change and so doesnt receive changes to events, so just updated the event before sending it to detailed page and parameters being too long smell probably is fine as unlikely to cause problems

**Comment by tmur647** [comment]
not too sure what sonar wants with MatchParent and WrapContent but think should be fine

**Review by deir905 — APPROVED** [review]
Nice work.

**Pull request merged**
