### PR TITLE
Fix/various bugs with home fragment and popular events

### LINKED ISSUE #102: Main swipe doesnt work
**Describe the bug**
Throws an error

**To Reproduce**
1. Go to main home
2. attempt to swipe

**Expected behavior**
Swipe to the desired side

**Screenshots**
NA

**Additional context**
NA

### LINKED ISSUE #108: Interesting an event does not correspond to the event displayed
**Describe the bug**
When adding an event to your interested list in the home view, it does not add the correct event.

**To Reproduce**
1. Go to home view
2. Click on Nope! on the first event to skip Speed Interviews
3. Click on Interested on the second event to add Interview Workshop
4. Go to interested tab and you'll see that it added Speed Interviews instead.

**Expected behavior**
It should add the displayed event

**Screenshots**

**Additional context**

### LINKED ISSUE #109: Popular events not persistent across devices and app instances
**Describe the bug**
If a user increments an event's popularity and reloads their app or uses another device. The popularity count is still 0. Also, becoming interested in an event will increase the wrong event's popularity count. In other words, the popularity event feature doesn't even work...

**To Reproduce**
1. Go to home fragment
2. Click on interested and notice the popularity count increase (and even for the wrong event sometimes)
3. Refresh app or go onto another device.
4. See that the popularity count is still 0.

**Expected behavior**
It is expected that the popularity count works and can be observed by other users.

**Screenshots**

**Additional context**

### LINKED ISSUE #110: App crashes when tapping on an event card in home fragment
**Describe the bug**
App crashes when tapping on an event card in home fragment because the fragment manager was not initialised.

**To Reproduce**
1. Go to home fragment
2. Click on an event card
3. App crashes

**Expected behavior**
Should navigate to detail page of the event

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by deir905**
~~Changed the popular events view pager to display all events, even ones interested, because it would make more sense to be able to gauge the popularity of events a user is going to as well.~~

This PR primarily fixes the popular events feature.

**Fixes a multitude of bugs.**
- Fixed issue where event cards could not be swiped.
- ~~Fixed issue where tapping on event cards in the home fragment crashed the app instead of navigating to the details page.~~
- Fixed issue where interesting in an event would not add the displayed intended event to the user's interest list.
- Fixed issue where the popularity count was not persistent across app instances, devices, users, etc. 
- Fixed issue where InterestedEvents fragment was not properly initialising user events, causing disinteresting action to reset popularity count to 0.
- Fixed the issue where if multiple users became interested in an event or removed an event from the interest list at the same time, the popularity count would only be incremented or decremented by 1.
- Fixed issue where interesting in an event would not add increment to the displayed intended event's popularity count.

~~Resolves #110~~
Resolves #109
Resolves #108 
Resolves #102

**EDIT:** Crossed out changes that I didn't notice was already done because I using an older version of the repository.

### CODE REVIEW

**Review by nbel806 — CHANGES_REQUESTED** [review]
Nice work fixing those, can you remove the extra files from sonarlint and deployment then ill aprove.

**Comment by deir905** [comment]
> Nice work fixing those, can you remove the extra files from sonarlint and deployment then ill aprove.

SonarLint files should be gone now.

**Comment by nbel806** [comment]
> > Nice work fixing those, can you remove the extra files from sonarlint and deployment then ill aprove.
> 
> SonarLint files should be gone now.

wait you added more. let me see if i can remove them from within github, or is that just you deleting them

**Review by nbel806 — APPROVED** [review]
LGTM

**Pull request merged**
