### PR TITLE
Feat/detailed fragment

### LINKED ISSUE #68: Details View of an Event
**Describe the feature**
A user should be able to view an event in more detail, and see all information regarding that event.

**Possible implementation(s)**
A possible implementation could be that a user can tap on an event that they would like some more information on and it will take them to a detailed view of the event where all information regarding the event is displayed, from this detailed view, a user could then also add the event to their liked events list.

**Additional context**
This would be a similar feature to online shopping applications where you get a brief look at an item and can tap on it to learn more about it, from there, you can add it to your watchlist. However, you can also add it to your watchlist without going to the detailed view. Check out some online shop apps like Amazon or TradeMe for some inspiration on a detailed view.

### PR DESCRIPTION
**Pull request by tmur647**
add functionality to clicking on event images either from the home page or the interested events page brings up  a detailed view of the event

to resolve issue #68

### CODE REVIEW

**Review by nbel806 — CHANGES_REQUESTED** [review]
Couple sonar cloud issues

**Review by Yxin-KaiByz — CHANGES_REQUESTED** [review]
There exists code smell issues which should be easily fixed
Also there is a bug related to the back button in detail view if user enter it from interested events. The back button should take user back to interested events instead of main

**Comment by tmur647** [comment]
implemented the changes, should be good to merge, the last code smell was just sonar saying to check whether a singleton is suitable, which I believe it is helpful in our case

**Review by Yxin-KaiByz — APPROVED** [review]

**Review by nbel806 — APPROVED** [review]
LGTM nice work

**Review by nbel806 — APPROVED** [review]
LGTM

**Pull request merged**
