### PR TITLE
Reduces duplication of code found in Firebase User Data Manager

### LINKED ISSUE #80: [A2 FEATURE] Reduces duplication of code found in Firebase User Data Manager
**Describe the feature**
Reduction of a duplication smell in Firebase user data manager

**Possible implementation(s)**
Made into one method which can be used for both situations

**Additional context**
Removing this reduces points for a big to occur and allows us to change code easier in the future

### PR DESCRIPTION
**Pull request by nbel806**
Reduces two very similar parts of code in favour of one method
Closes #80

### CODE REVIEW

**Review by tmur647 — CHANGES_REQUESTED** [review]
looks good, removes the duplicate code well, there are 2 code smells that got brought up by sonar that could easily be fixed and I was also wondering if it would be better for maintainability to change getEvents(True) to getEvents(INTERESTED) where INTERESTED is a final string so when calling it it is easier to know what the argument means instead of using a boolean

**Comment by nbel806** [comment]
> looks good, removes the duplicate code well, there are 2 code smells that got brought up by sonar that could easily be fixed and I was also wondering if it would be better for maintainability to change getEvents(True) to getEvents(INTERESTED) where INTERESTED is a final string so when calling it it is easier to know what the argument means instead of using a boolean

Not sure that would work to well, other places where the method is called would then need to define the final string. Unless I'm missunderstanding

**Comment by tmur647** [comment]
ye didnt think about that, the way you did it works fine

**Review by tmur647 — APPROVED** [review]
lgtm

**Pull request merged**
